name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Build and run tests
        run: mvn clean test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: master
          path: master

      - name: Show files
        run: ls -R

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: master
          allure_history: allure-history
          allure_report: allure-report
          allure_results: target/allure-results

#      - name: Print token
#        if: always()
#        run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish test report
#        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
          publish_branch: master
          publish_dir: allure-history